#!/usr/bin/env bash
#PBS -N runORSON
#PBS -m n
#PBS -q sequentiel
#PBS -l mem=10G
#PBS -l walltime=72:00:00

#activate nextflow environment
. /etc/profile.d/modules.sh
module purge
. /appli/bioinfo/nextflow/23.10.0/env.sh
module load singularity/3.4.1

#import singularity images
cd $PBS_O_WORKDIR

#nextflow temp directory
export NXF_TEMP=$SCRATCH/.nxf_temp_orson
mkdir -p $NXF_TEMP

##################################################################################################
##### DONT FORGET TO CUSTOMIZE ORSON TO FIT YOUR DATASET                                     #####
##### NEED TO COMPLETE CUSTOM.CONFIG FILE BEFORE RUNNING OR ADD ARGUMENTS :                  #####
##### HAVE A LOOK AT https://gitlab.ifremer.fr/bioinfo/orson/-/tree/master/docs              #####
##################################################################################################
cd $PBS_O_WORKDIR

# For ORSON TEST
# nextflow run main.nf -profile test,singularity -c /appli/bioinfo/orson/1.0.0/ifremer.config &> orson.log 2>&1

# For custom usage of ORSON.
nextflow run main.nf -profile custom,singularity -c /appli/bioinfo/orson/1.0.0/ifremer.config --downloadDB_enable false  &> orson.log 2>&1

# For resume a previous ORSON analysis
# nextflow run main.nf -profile custom,singularity -c /appli/bioinfo/orson/1.0.0/ifremer.config --downloadDB_enable false -resume &> orson.log 2>&1

#deactivate nextflow environment and module
. /appli/bioinfo/nextflow/23.10.0/delenv.sh
module purge

